In [20]:
import numpy as np
from numpy import linalg as LA
A=np.array([[1,2],[3,4]])
print(A)
#M = np.matrix([[2, -1, 0],
               #[-1, 2, -1],
               #[0, -1, 2]])

x,y=LA.eig(A)
print(x)
#temp=LA.eigvals(M)
#print(temp)
condition_number=np.max(np.abs(x))/np.min(np.abs(x))
print(condition_number)

[[1 2]
 [3 4]]
[-0.37228132  5.37228132]
14.430703308172536


In [30]:
M2=np.arange(1,10).reshape(3,3)
print(M2)
m2x,m2y=LA.eig(M2)
M_condition_number=np.max(np.abs(m2x))/np.min(np.abs(m2x))
print(M_condition_number)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1.6514539124698442e+16


In [35]:
M3=np.matrix([[1,2,3],[4,5,6],[7,7,8]])
print(M3)
m3x,m3y=LA.eig(M3)
M3_condition_number=(np.max(np.abs(m3x))/np.min(np.abs(m3x)))
print(M3_condition_number)

[[1 2 3]
 [4 5 6]
 [7 7 8]]
101.51067742356962


In [43]:
y=np.arange(1,100)
x=(1/y)*y-1

for eachval in x:
    if eachval!=0:
        print(eachval)

-1.1102230246251565e-16
-1.1102230246251565e-16


In [95]:
A=np.matrix([[1,2,10],[4,5,6],[7,8,9]])
determinant=LA.det(A)
print(determinant)

I=np.identity(3)
print(I)
B=A+0.0001*I


-21.00000000000001
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [97]:
print("Matirx B is ", B)
detB=LA.det(B)
print("Determinant of B is",detB)
Binv=LA.inv(B)

print("Inverse of B is",Binv)

C=Binv@B
print("Matrix C is",C)

largest_diff=C-I
error=np.max(np.abs(largest_diff))
print("Largest difference is ",error)

Matirx B is  [[ 1.0001  2.     10.    ]
 [ 4.      5.0001  6.    ]
 [ 7.      8.      9.0001]]
Determinant of B is -21.006699849999006
Inverse of B is [[ 0.14274493 -2.9514298   1.80899429]
 [-0.28560412  2.90378786 -1.61850268]
 [ 0.1428449  -0.28558508  0.14278302]]
Matrix C is [[ 1.00000000e+00  1.77635684e-15  0.00000000e+00]
 [ 6.66133815e-16  1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  0.00000000e+00  1.00000000e+00]]
Largest difference is  1.7763568394002505e-15
